build/root/usr/local/bin/run: do not print git commit notes in the CI run info

diff --git a/build/root/usr/local/bin/run b/build/root/usr/local/bin/run
--- a/build/root/usr/local/bin/run
+++ b/build/root/usr/local/bin/run
@@ -38,7 +38,7 @@ fi
 if [[ "${INSIDE_CI_IMAGE:-}" == "y" ]]; then
     echo "===> $0 $@ <=="
 
-    git show -s || echo "Could not access git history ..."
+    git show --quiet || echo "Could not access git history ..."
     echo
     oc version
     echo
