build/root/usr/local/bin/run: fix indentation
Signed-off-by: Kevin Pouget <kpouget@redhat.com>

diff --git a/build/root/usr/local/bin/run b/build/root/usr/local/bin/run
--- a/build/root/usr/local/bin/run
+++ b/build/root/usr/local/bin/run
@@ -13,8 +13,8 @@ set -o nounset
 
 if [[ -z "${KUBECONFIG}" ]]
 then
-		echo "No kubeconfig, can't continue"
-		exit 1
+    echo "No kubeconfig, can't continue"
+    exit 1
 fi
 echo "Kubeconfiug found at ${KUBECONFIG}, proceeding with tests"
 
@@ -27,21 +27,21 @@ cd ${WORK_DIR}
 
 INVENTORY_ARG="-i inventory/hosts"
 while true; do
-	case ${1:-} in
+    case ${1:-} in
         "gpu-ci")
-		exec ansible-playbook ${INVENTORY_ARG} ${ANSIBLE_OPTS} playbooks/nvidia-gpu-operator-ci.yml
-	;;
+	    exec ansible-playbook ${INVENTORY_ARG} ${ANSIBLE_OPTS} playbooks/nvidia-gpu-operator-ci.yml
+	    ;;
 	"psap-ci")
-		exec ansible-playbook ${INVENTORY_ARG} ${ANSIBLE_OPTS} playbooks/openshift-psap-ci.yml
-	;;
+	    exec ansible-playbook ${INVENTORY_ARG} ${ANSIBLE_OPTS} playbooks/openshift-psap-ci.yml
+	    ;;
         -*)
             echo "Unknown option: ${1:-}"
             exit 1
-        ;;
+            ;;
 	*)
-		break
-	;;
-	esac
+	    break
+	    ;;
+    esac
 done
 
 exit 0
